services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: caddy
    restart: unless-stopped

    ports:
      - "100.68.125.75:80:80"
      - "100.68.125.75:443:443"
      - "100.68.125.75:443:443/udp"
    environment:
      PORKBUN_API_KEY: ${PORKBUN_API_KEY}
      PORKBUN_API_SECRET_KEY: ${PORKBUN_API_SECRET_KEY}

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  caddy_data:
  caddy_config: